# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hello_cicd',
                'doc_host': 'https://lzhang2.github.io',
                'git_url': 'https://github.com/lzhang2/hello_cicd',
                'lib_path': 'hello_cicd'},
  'syms': {'hello_cicd.core': {'hello_cicd.core.foo': ('core.html#foo', 'hello_cicd/core.py')}}}
